### ISSUE TITLE
Processing Gathers?

### ISSUE THREAD

**Issue by RaphiePS** [stevegraham/twilio-js#4]
Is there any built-in functionality for processing responses to a Gather? If not, how would I go about doing that?

**Comment by stevegraham** [comment]
hey dude. what do you mean? to respond to a gather you just need to return more twiml so twilio knows what to do with the call. what you trying to do my man? maybe i can help!

**Comment by RaphiePS** [comment]
Whoops, sorry for the ambiguity. I'd like to respond with a different message based on what keys they pressed.

**Comment by stevegraham** [comment]
What you need is a HTTP server so Twilio can send the digits collected during a Gather. When Twilio does this the correct response is more TwiML describing how you want the call to continue based on that input, e.g. A menu saying "Press 1 for sales. Press 2 for marketing… etc" When Twilio makes a request to your server with the digit presses, your app returns further TwiML with, for example a sub-menu for sales.
